### ISSUE TITLE
Problem with running inference

### ISSUE THREAD

**Issue by ronnnhui** [neosapience/mlp-singer#3]
![image](https://user-images.githubusercontent.com/37474567/140004762-9593ba0b-d83b-4b8f-a2cd-ff14c55ec380.png)

Plz help!

**Comment by jaketae** [comment]
Hello @zhennronnnhui, thanks for opening this issue!

Can you double check that there is a `config.json` file in the `checkpoints/default` directory (where `model.pt` is), and that the `config.json` file contains a `model` entry? If you have cloned this directory as is, you should have this file:

https://github.com/neosapience/mlp-singer/blob/b6a546fc6fbeb17a6220320a596ea1542ee3e509/checkpoints/default/config.json#L1-L3

**Comment by Rt1z** [comment]
> Hello @zhennronnnhui, thanks for opening this issue!
> 
> Can you double check that there is a `config.json` file in the `checkpoints/default` directory (where `model.pt` is), and that the `config.json` file contains a `model` entry? If you have cloned this directory as is, you should have this file:
> 
> https://github.com/neosapience/mlp-singer/blob/b6a546fc6fbeb17a6220320a596ea1542ee3e509/checkpoints/default/config.json#L1-L3

oh ok, problem solved!  Great work btw! :)
