### ISSUE TITLE
inference wav worse than demo wav

### ISSUE THREAD

**Issue by zhangsanfeng86** [neosapience/mlp-singer#4]
Thank you for release.
After run "python inference.py --checkpoint_path checkpoints/default/model.pt", it generate wav, it worse than demo
[little_star_generated_e2e.zip](https://github.com/neosapience/mlp-singer/files/7630486/little_star_generated_e2e.zip)
.

**Comment by jaketae** [comment]
Hello @zhangsanfeng86, thanks for opening this issue.

As noted in the original paper, we used an in-house variant of HiFi-GAN, which was additionally fine-tuned on the Children's Song dataset. The code base, as provided in this repository, uses the universal HiFi-GAN checkpoint, so the quality of synthesized results is likely going to be perceptibly worse than those on the demo webpage. For better results, I would recommend that you first try fine-tuning the HiFi-GAN vocoder on CSD. 

Please let me know if you have any more questions or concerns. Thanks!

**Comment by zhangsanfeng86** [comment]
OK， thank you for quick and helpful reply !
