### ISSUE TITLE
python: can't open file 'inference_e2e.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ghost** [neosapience/mlp-singer#7]
Congratulations, and thank you for sharing your work.

I'm trying to run inference according to the readme, and get this error:
```
$ python inference.py --checkpoint_path checkpoints/default/model.pt
python: can't open file 'inference_e2e.py': [Errno 2] No such file or directory
```
This seems to be due to line 56-59 in inference.py:
```
    subprocess.call(
        f"cd hifi-gan; python inference_e2e.py --checkpoint_file {args.hifi_gan} --output_dir ../{save_path}",
        shell=True,
    )
```
The `inference_e2e.py` seems to be missing in the repository.

**Comment by jaketae** [comment]
Hey @Hamsteau, thank you for your interest in this work. 

`inference_e2e.py` is indeed not part of this repository. Instead, it comes from [HiFi-GAN](https://github.com/jik876/hifi-gan/tree/4769534d45265d52a904b850da5a622601885777), which is configured as a `git` submodule of this repository. So if you have run `git clone --recurse-submodules https://github.com/neosapience/mlp-singer.git`, you should see a directory called `hifi-gan` with `inference_e2e.py`. You might have just `git clone`-ed the repository without the submodule.

Let me know if this resolves the problem!

**Comment by ghost** [comment]
Thank you for your reply! My apologies, I had indeed missed the `--recurse-submodules` part. Cloning it again, correctly, resolved this issue.
