### ISSUE TITLE
inference.py - The specified path could not be found.

### ISSUE THREAD

**Issue by jungtaekyung1** [neosapience/mlp-singer#8]
Thanks for uploading a nice project. I have an obstacle following your project.
I'm trying to run inference according to the readme, and get this error:
```
지정된 파일을 찾을 수 없습니다 -> The specified file could not be found
```
The above error occurs in the statement below.
```
subprocess.call(
        f"cd hifi-gan; python inference_e2e.py --checkpoint_file {args.hifi_gan} --output_dir ../{save_path}",
        shell=True,
    )
```

To prevent the same problem as #7 , I followed the readme and faithfully performed all the processes including downloading gitclone and checkpoint. Why do these problems occur?

**Comment by jungtaekyung1** [comment]
I solved the problem above. An important point in the above problem is
```
cd hifi-gan;
```
The above code did not run normally, so inference_e2e.py could not be found, and it was difficult to find the pretrained g_02500000 file and sample folder.

Therefore, I modified some parts of inference.py.
```
  os.chdir('E:\jtk-svs\mlp-singer\hifi-gan')
    subprocess.call(
        f"python inference_e2e.py --checkpoint_file {args.hifi_gan} --output_dir ../samples",
        shell=True,
    )
```

**Comment by jaketae** [comment]
Hello @jungtaekyung1, thanks for filing this issue. I'm glad to hear that you were able to fix the problem. Best of luck and happy new year!
